### ISSUE TITLE
path not found http://disy.github.com/perclipse/

### ISSUE THREAD

**Issue by sopan-test** [sebastiangraf/perfidix#9]
While installing plugin in eclipse neon, getting error http://disy.github.com/perclipse/ path not found.

**Comment by sebastiangraf** [comment]
indeed, the path changed to http://sebastiangraf.github.io/perclipse/
Where did you find the old link? Eclipse marketplace?

**Comment by sebastiangraf** [comment]
deprecated links in eclipse marketplace: https://marketplace.eclipse.org/content/perclipse-perfidix-eclipse-plugin

**Comment by sebastiangraf** [comment]
links fixed.
